baseurl = "https://hadoop.apache.org"
title = "Apache Hadoop"
copyright = "&copy; 2017 Your Name"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
uglyurls = true

[[menu.main]]
  name = "Download"
  url = "releases.html"
  weight = 1


[[menu.main]]
  name = "Documentation"
  identifier = "documentation"
  weight = 2

[[menu.main]]
   name = "Latest"
   parent = "documentation"
   url = "http://hadoop.apache.org/docs/current/"

[[menu.main]]
   name = "Stable"
   parent = "documentation"
   url = "http://hadoop.apache.org/docs/stable/"




[[menu.main]]
   name = "Community"
   identifier = "community"
   weight = 3



[[menu.main]]
   name = "Development"
   identifier = "development"
   weight = 4

[[menu.main]]
  name = "How to Contribute"
  url = "https://wiki.apache.org/hadoop/HowToContribute"
  parent = "development"

[[menu.main]]
   name = "Help"
   identifier = "help"
   weight = 5

[[menu.main]]
   name = "Buy Stuff"
   url = "http://www.cafepress.com/hadoop"
   parent = "help"

[[menu.main]]
   name = "Sponsorshop"
   url = "http://www.apache.org/foundation/sponsorship.html"
   parent = "help"

[[menu.main]]
   name = "Thanks"
   url = "http://www.apache.org/foundation/thanks.html"
   parent = "help"

[[menu.apache]]
   name = "License"
   url = "http://www.apache.org/foundation/thanks.html"



# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
